### ISSUE TITLE
What does "Number of Decensor Variations" mean?

### ISSUE THREAD

**Issue by Nughu** [Deepshift/DeepCreamPy#3]
In the app, I am presented with the option to choose a "Number of Decensor Variations":
![image](https://user-images.githubusercontent.com/112648460/214317676-fc77dbe3-7e57-4468-bab0-5feb9b1bd509.png)

What does this mean and therefore which setting do I need to select for which purpose?

**Comment by TrippieTabz** [comment]
the ai will make 4 different versions of the photo decensored so u can pick the one that woked the best basically

**Comment by naphteine** [comment]
Thank you @TrippieTabz  for your kind reply. I think it's okay to mark this issue closed now.
