### ISSUE TITLE
Could you add a script for clearing folders with only one button and not manually deleting files

### ISSUE THREAD

**Issue by ghost** [Deepshift/DeepCreamPy#7]
So here is the code I made. Take it to consideration. It is helpful for me to clear input/output folders after decensoring videos. As manually opening 3 folders and deleting all files is too long. I use it as a file in the folder and adding a shortcut should as well work. If you implement it to the main UI if it is usefull for you.
You can use this code or modify it as you wish.

P.S. Can't write code in a good way(makrdown messing up the code even if I use code fomating) here so adding a text file.
[ClearDCPFolders.txt](https://github.com/Deepshift/DeepCreamPy/files/14805688/ClearDCPFolders.txt)

`
import os
from typing import Union

def clear_folder(folder_path: Union[str, bytes]) -> None:
    try:
        for filename in os.listdir(folder_path):
            file_path = os.path.join(folder_path, filename)
            if os.path.isfile(file_path):
                os.remove(file_path)
            elif os.path.isdir(file_path):
                clear_folder(file_path)
        print(f"Content of '{folder_path}' cleared successfully.")
    except Exception as e:
        print(f"Error clearing content of '{folder_path}': {e}")

def main():
    folders_to_clear = ["decensor_input", "decensor_input_original", "decensor_output"]
    for folder in folders_to_clear:
        folder_path = os.path.join(os.path.dirname(__file__), folder)
        clear_folder(folder_path)

if __name__ == "__main__":
    main()
`

**Comment by naphteine** [comment]
Hello,

Sorry for late reply. I just tested and added the script you provided. Thank you for your work! I will leave this issue open until I add the button. If the script breaks anything just write here. Thanks again!!

**Comment by naphteine** [comment]
As of right now the cleanup script is included in the base and there's also new checkbox that cleans up input directories after the process, I think we can mark this issue closed. Thanks for initial work and suggestion.
